### ISSUE TITLE
Failed to connect before the deadline URL:grpc://peer0.org1.example.com:17051

### ISSUE THREAD

**Issue by johndacost** [horeaporutiu/VSCodeLocalNetwork#5]
Hi,

I follow your tuto from https://www.youtube.com/watch?v=r77p-8k4Mpk and when I try to run the invoke.js I got this error : 

```
$ node invoke.js
Connected to Fabric gateway.
Connected to mychannel.

Submit hello world transaction.
2019-09-16T11:01:16.578Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpc://peer0.org1.example.com:17051
2019-09-16T11:01:16.580Z - warn: [DiscoveryEndorsementHandler]: _build_endorse_group_member >> G0:0 - endorsement failed - Error: Failed to connect before the deadline URL:grpc://peer0.org1.example.com:17051e URL:grpc://peer0.org1.example.com:17051
Error processing transaction. Error: Endorsement has failed
Error: Endorsement has failed                                                                                                                                         orsementHandler.js:184:19)
    at DiscoveryEndorsementHandler._endorse (C:\DEV\CIB\cib-poc-inotex\VSCodeLocalNetwork\node_modules\fabric-network\node_modules\fabric-client\lib\impl\DiscoveryEndorsementHandler.js:184:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Disconnect from Fabric gateway.
done
```

I use the right port binding for my case. So I updated the network.yaml : 
```
...
peers:
  peer0.org1.example.com:
    # this URL is used to send endorsement and query requests
    url: grpc://0.0.0.0:17051

    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      request-timeout: 120001
...
```

docker ps :
```
$ docker ps
CONTAINER ID        IMAGE                                                                                                                            COMMAND
        CREATED             STATUS              PORTS                                         NAMES
49deae4dab3f        fabricvscodelocalfabric-peer0.org1.example.com-contract-0.0.1-c20165c31d99312b260b332f5b830351e392e550640e935758e9d548ccee3add   "/bin/sh -c 'cd /usr…"   41 minutes ago      Up 41 minutes                                                     fabricvscodelocalfabric-peer0.org1.example.com-contract-0.0.1
7b0ba554cc50        hyperledger/fabric-peer:1.4.2                                                                                                    "peer node start"        About an hour ago   Up About an hour    0.0.0.0:17051-17052->17051-17052/tcp          fabricvscodelocalfabric_peer0.org1.example.com
62d4226f2cd1        hyperledger/fabric-ca:1.4.2                                                                                                      "sh -c 'fabric-ca-se…"   About an hour ago   Up About an hour    7054/tcp, 0.0.0.0:17054->17054/tcp            fabricvscodelocalfabric_ca.org1.example.com
040e4d8684ef        hyperledger/fabric-orderer:1.4.2                                                                                                 "orderer"        
        About an hour ago   Up About an hour    7050/tcp, 0.0.0.0:17050->17050/tcp            fabricvscodelocalfabric_orderer.example.com
8fef28e9224e        gliderlabs/logspout                                                                                                              "/bin/logspout"  
        About an hour ago   Up About an hour    0.0.0.0:17056->80/tcp                         fabricvscodelocalfabric_logspout
532c24a97818        hyperledger/fabric-couchdb:0.4.15                                                                                                "tini -- /docker-ent…"   About an hour ago   Up About an hour    4369/tcp, 9100/tcp, 0.0.0.0:17055->5984/tcp   fabricvscodelocalfabric_couchdb
```

Any idea what wrong with my config ?

Here my docker version : 

```
λ docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by Alaaziz** [comment]
did you solve this problem ? becuse i'm facing the same error

**Comment by marciofk** [comment]
Hi johndacost, probably you are connecting to the network using discovery enabled to augment the network. If you are running from local docker containers, you should enable discovery as localhost to translate address from the docker network to the localhost. In summary, you should have something like this in your client when connecting.

` await gateway.connect(ccp, { wallet, identity: admin, discovery: {"enabled": true,"asLocalhost": true} });
`

Apparently, your _asLocalHost_ value is marked as false.

**Comment by Alaaziz** [comment]
How can i do that ? Can you please provide me with steps

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marciofk** [comment]
Alaaziz, if you are using the E-vote example provided by Horea Porutiu, take a look at the configuration file at web-app/server/config.json. You will find the _gatewayDiscovery_ configuration.

**Comment by Alaaziz** [comment]
I double check and I couldn’t find any file with the same extension you mentiond

On 24 Nov 2019, at 9:07 PM, Marcio Fuckner <notifications@github.com<mailto:notifications@github.com>> wrote:

web-app/server/config.json.

**Comment by marciofk** [comment]
Hi Alaaziz,

I do not have enough information to help you given the very short description. Apparently, the problem happens when you try to connect to the network using the gateway object.

If this is the case, you can modify the call, adding more information via the connection options, enabling discovery. I am assuming you are running Docker containers from your local computer. 

```
let connectionOptions = {
   identity: identityLabel,
   wallet: wallet,
   gatewayDiscovery: {
      enabled: true,
      asLocalhost: true
   }	      
};
await gateway.connect(connectionProfile, connectionOptions);
```

If it does not work, then you should provide more information (detailed error messages, code snippets)

**Comment by samadsidd** [comment]
Has anyone solved this..
I am also getting this error @marciofk

**Comment by mikehammond** [comment]
Based on the explanation that @marciofk gave, I am having a VM on Azure which is hosting my Fabric Network and I want to connect to it remotely, After changing enabled to false and asLocalhost to false, it worked.

Mine now looks like
```
let connectionOptions = {
   identity: identityLabel,
   wallet: wallet,
   gatewayDiscovery: {
      enabled: false,
      asLocalhost: false
   }	      
};
await gateway.connect(connectionProfile, connectionOptions);
```

But when connecting from the same machine hosting the Fabric Network, you should be using
```
let connectionOptions = {
   identity: identityLabel,
   wallet: wallet,
   gatewayDiscovery: {
      enabled: true,
      asLocalhost: true
   }	      
};
await gateway.connect(connectionProfile, connectionOptions);
```

Thanks @marciofk

**Comment by csquan** [comment]
@mickeymondmest,@mickeymondmest,I have follow https://github.com/hyperledger/blockchain-explorer to run docker-compose.yaml step by step,met same wrong,and as you tips,there is still  errors:
explorer.mynetwork.com      | 2020-07-31T07:41:00.567Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://127.0.0.1:7051, connected:false, connectAttempted:true
explorer.mynetwork.com      | 2020-07-31T07:41:00.570Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://127.0.0.1:7051 timeout:3000
explorer.mynetwork.com      | 2020-07-31T07:41:00.572Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer0.org1.example.com due to Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://127.0.0.1:7051, connected:false, connectAttempted:true
explorer.mynetwork.com      | [2020-07-31T07:41:00.575] [ERROR] FabricGateway - Error: Endorser must be connected
explorer.mynetwork.com      | [2020-07-31T07:41:00.577] [ERROR] FabricClient - { ExplorerError: [ 'Failed to create wallet, please check the configuration, and valid file paths' ]
explorer.mynetwork.com      |     at FabricGateway.initialize (/opt/explorer/app/platform/fabric/gateway/FabricGateway.js:135:10)
explorer.mynetwork.com      |     at process._tickCallback (internal/process/next_tick.js:68:7)
explorer.mynetwork.com      |   name: 'ExplorerError',
explorer.mynetwork.com      |   message:
explorer.mynetwork.com      |    '[ \'Failed to create wallet, please check the configuration, and valid file paths\' ]'

**Comment by mikehammond** [comment]
@csquan Do you have a Hyperledger Fabric Network running on your localhost?

**Comment by csquan** [comment]
yes，all step is follow the official web.

**Comment by csquan** [comment]
my docker ps info:
696c48697140        dev-peer0.org2.example.com-mycc-v0-22355527861a6e34150a8bd05d8d30fd2c991d18871620fab4e32394679f19c6   "chaincode -peer.add…"   6 hours ago         Up 6 hours                                                                 dev-peer0.org2.example.com-mycc-v0
935ff7a9ef6b        dev-peer0.org1.example.com-mycc-v0-f021beca29998638e0bb7caa7af8fda7f1e709518214a3181d259abcb2347093   "chaincode -peer.add…"   6 hours ago         Up 6 hours                                                                 dev-peer0.org1.example.com-mycc-v0
bd1a4c5fdef5        hyperledger/fabric-peer                                                                               "peer node start"        6 hours ago         Up 6 hours                0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp   peer0.org2.example.com
f2e32c427f1e        hyperledger/fabric-peer                                                                               "peer node start"        6 hours ago         Up 6 hours                0.0.0.0:8056->7051/tcp, 0.0.0.0:8058->7053/tcp   peer1.org2.example.com
b12e2918595d        hyperledger/fabric-peer                                                                               "peer node start"        6 hours ago         Up 6 hours                0.0.0.0:7056->7051/tcp, 0.0.0.0:7058->7053/tcp   peer1.org1.example.com
56b5c42712ea        hyperledger/fabric-peer                                                                               "peer node start"        6 hours ago         Up 6 hours                0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
7a17745b761d        hyperledger/fabric-ca                                                                                 "sh -c 'fabric-ca-se…"   6 hours ago         Up 6 hours                0.0.0.0:7054->7054/tcp                           ca_peerOrg1
d43e629ca203        hyperledger/fabric-orderer                                                                            "orderer"                6 hours ago         Up 6 hours                0.0.0.0:7050->7050/tcp                           orderer.example.com
81b2fe5f9124        hyperledger/fabric-ca                                                                                 "sh -c 'fabric-ca-se…"   6 hours ago         Up 6 hours                0.0.0.0:8054->7054/tcp                           ca_peerOrg2
I have start fabric-samples/balance-transfer network and copy crypto dir to explorer dir as offcial said.

**Comment by mikehammond** [comment]
@csquan 
![image](https://user-images.githubusercontent.com/54583027/89016371-83a83d80-d310-11ea-904c-89d0ae560f1a.png)
In your docker-compose.yaml for the Blockchain Explorer set the DISCOVERY_AS_LOCALHOST=true for the envinroments.

**Comment by csquan** [comment]
I have change first_network.json to balance-transfer.json and others same as official.
now errors:
2020-07-31T08:48:41.683Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054], stack=Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
explorer.mynetwork.com      |     at ClientRequest.request.on (/opt/explorer/node_modules/fabric-ca-client/lib/FabricCAClient.js:487:12)
explorer.mynetwork.com      |     at ClientRequest.emit (events.js:198:13)
explorer.mynetwork.com      |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
explorer.mynetwork.com      |     at TLSSocket.emit (events.js:198:13)
explorer.mynetwork.com      |     at emitErrorNT (internal/streams/destroy.js:91:8)
explorer.mynetwork.com      |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
explorer.mynetwork.com      |     at process._tickCallback (internal/process/next_tick.js:63:19)
explorer.mynetwork.com      | [2020-07-31T08:48:41.686] [ERROR] FabricGateway - Error instantiating FabricCAServices  Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]

**Comment by mikehammond** [comment]
@csquan Your new error is about you not having a CA running on PORT 7054.
But why did you change from first_network.json to balance-transfer.json?

**Comment by csquan** [comment]
first ,I have run fabric-samples/balance-transfer network and  there two json files in connection-profile .
second,my docker ps info show port 7054 is ca listening.

**Comment by csquan** [comment]
In fabric-samples/balance-transfer,I have run testAPI.sh,and all is okey.
I copy crypto dir to explorer dir and do other steps which official tell  .

**Comment by csquan** [comment]
I have edit ca name in balance-transfer.json and the error go away.
but meet first erros:
explorer.mynetwork.com      | 2020-07-31T09:16:51.670Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
explorer.mynetwork.com      | 2020-07-31T09:16:51.674Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://localhost:7051 timeout:3000
explorer.mynetwork.com      | 2020-07-31T09:16:51.675Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer0.org1.example.com due to Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
explorer.mynetwork.com      | [2020-07-31T09:16:51.680] [ERROR] FabricGateway - Error: Endorser must be connected
explorer.mynetwork.com      | [2020-07-31T09:16:51.686] [ERROR] FabricClient - { ExplorerError: [ 'Failed to create wallet, please check the configuration, and valid file paths' ]
explorer.mynetwork.com      |     at FabricGateway.initialize (/opt/explorer/app/platform/fabric/gateway/FabricGateway.js:135:10)
explorer.mynetwork.com      |     at process._tickCallback (internal/process/next_tick.js:68:7)
explorer.mynetwork.com      |   name: 'ExplorerError',
explorer.mynetwork.com      |   message:
explorer.mynetwork.com      |    '[ \'Failed to create wallet, please check the configuration, and valid file paths\' ]' }

**Comment by csquan** [comment]
so why can not connect to endorser?

**Comment by csquan** [comment]
Is master branch of explorer can not run?or I should checkout to some version?

**Comment by csquan** [comment]
can someone knows how to solve it?

**Comment by csquan** [comment]
I have checkout other version,errors still exist same:
 Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
any help would be appreciated.

**Comment by csquan** [comment]
anyone knows？

**Comment by csquan** [comment]
7051 does exist and tlscert I have copy from balance-transfer as official said.
But still can not connect .

**Comment by csquan** [comment]
wondering if someone could help me with this error

**Comment by csquan** [comment]
？anybody

**Comment by csquan** [comment]
I use first-network and blockchain-explorer done well.
but now I use balance-transfer network,so I cp app/platform/fabric/connection-profile/balance-transfer.json to local dir
and edit path and name of certfile .edit docker-compose.yaml's network name to artifacts_default and run .
It show explorer.mynetwork.com      | 2020-08-10T01:22:20.221Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054], stack=Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
explorer.mynetwork.com      |     at ClientRequest.request.on (/opt/explorer/node_modules/fabric-ca-client/lib/FabricCAClient.js:487:12)
so ,what happened? 7054 is exist which ca1 works.
here is my docker ps:
root@csquan-Virtual-Machine:/var/hyperledger# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a972ec9e8c6c        hyperledger/fabric-peer      "peer node start"        8 minutes ago       Up 8 minutes        0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
1a210fa65c8f        hyperledger/fabric-peer      "peer node start"        8 minutes ago       Up 8 minutes        0.0.0.0:7056->7051/tcp, 0.0.0.0:7058->7053/tcp   peer1.org1.example.com
448d5bc94903        hyperledger/fabric-peer      "peer node start"        8 minutes ago       Up 8 minutes        0.0.0.0:8056->7051/tcp, 0.0.0.0:8058->7053/tcp   peer1.org2.example.com
c9e02a87eff2        hyperledger/fabric-peer      "peer node start"        8 minutes ago       Up 8 minutes        0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp   peer0.org2.example.com
ff88344babf8        hyperledger/fabric-ca        "sh -c 'fabric-ca-se…"   8 minutes ago       Up 8 minutes        0.0.0.0:7054->7054/tcp                           ca_peerOrg1
123feba184d1        hyperledger/fabric-ca        "sh -c 'fabric-ca-se…"   8 minutes ago       Up 8 minutes        0.0.0.0:8054->7054/tcp                           ca_peerOrg2
137962b381d6        hyperledger/fabric-orderer   "orderer"                8 minutes ago       Up 8 minutes        0.0.0.0:7050->7050/tcp

**Comment by csquan** [comment]
I  use first-network and blockchain-explorer done well.
but now I use balance-transfer network,so I cp app/platform/fabric/connection-profile/balance-transfer.json to local dir
and edit path and name of certfile .edit docker-compose.yaml's network name to artifacts_default and run .
It show :{ Error: 14 UNAVAILABLE: failed to connect to all addresses
explorer.mynetwork.com      |     at Object.exports.createStatusError (/opt/explorer/node_modules/grpc/src/common.js:91:15)
explorer.mynetwork.com      |     at Object.onReceiveStatus (/opt/explorer/node_modules/grpc/src/client_interceptors.js:1209:28)
explorer.mynetwork.com      |     at InterceptingListener._callNext (/opt/explorer/node_modules/grpc/src/client_interceptors.js:568:42)
explorer.mynetwork.com      |     at InterceptingListener.onReceiveStatus (/opt/explorer/node_modules/grpc/src/client_interceptors.js:618:8)
explorer.mynetwork.com      |     at callback (/opt/explorer/node_modules/grpc/src/client_interceptors.js:847:24)

**Comment by cold-briu** [comment]
I'm facing same issue. I have tried following settings on docker composer: 
      - CORE_PEER_TLS_ENABLED=true
      - DISCOVERY_AS_LOCALHOST=true

Also, my code is just as:
    await gateway.connect(ccp, { wallet, identity: email, discovery: { enabled: true, asLocalhost: true } });
Following line didn't work either
    await gateway.connect(ccp, { wallet, identity: 'admin', discovery: { enabled: true, asLocalhost: true } });

**Comment by JuWeber99** [comment]
Hey guys! 
So .. me too!
if i run the application talking to the endorsers on my local machine with npm start everything works fine
but if i use a local docker container i also get:

2020-08-27T12:29:39.144Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
2020-08-27T12:29:39.144Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.nexnet.hypersub.com url:grpcs://localhost:7051 timeout:3000
2020-08-27T12:29:39.144Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer0.nexnet.hypersub.com due to Error: Failed to connect before the deadline on Endorser- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
2020-08-27T12:29:42.145Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Discoverer- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
2020-08-27T12:29:42.146Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.nexnet.hypersub.com url:grpcs://localhost:7051 timeout:3000
Failed to get network connection: Error: Failed to connect before the deadline on Discoverer- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true


i have also set the discovery option for localhost as true.. anyone has a clue?

PS: i have also tried pinging the peer containers with hostname resolution.. which WORKS

**Comment by johndacost** [comment]
> Hi Alaaziz,
> 
> I do not have enough information to help you given the very short description. Apparently, the problem happens when you try to connect to the network using the gateway object.
> 
> If this is the case, you can modify the call, adding more information via the connection options, enabling discovery. I am assuming you are running Docker containers from your local computer.
> 
> ```
> let connectionOptions = {
>    identity: identityLabel,
>    wallet: wallet,
>    gatewayDiscovery: {
>       enabled: true,
>       asLocalhost: true
>    }	      
> };
> await gateway.connect(connectionProfile, connectionOptions);
> ```
> 
> If it does not work, then you should provide more information (detailed error messages, code snippets)

Sorry about the late response... But yes you was right  and this solve my problem ! Thanks ! :)

**Comment by percy6081** [comment]
> Hey guys!
> So .. me too!
> if i run the application talking to the endorsers on my local machine with npm start everything works fine
> but if i use a local docker container i also get:
> 
> 2020-08-27T12:29:39.144Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
> 2020-08-27T12:29:39.144Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.nexnet.hypersub.com url:grpcs://localhost:7051 timeout:3000
> 2020-08-27T12:29:39.144Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer0.nexnet.hypersub.com due to Error: Failed to connect before the deadline on Endorser- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
> 2020-08-27T12:29:42.145Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Discoverer- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
> 2020-08-27T12:29:42.146Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.nexnet.hypersub.com url:grpcs://localhost:7051 timeout:3000
> Failed to get network connection: Error: Failed to connect before the deadline on Discoverer- name: peer0.nexnet.hypersub.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
> 
> i have also set the discovery option for localhost as true.. anyone has a clue?
> 
> PS: i have also tried pinging the peer containers with hostname resolution.. which WORKS

did you solved your problem?

**Comment by IbrahimAlgadi** [comment]
You can solve this issue by defining the network where the peer and the artifacts are in 

![image](https://user-images.githubusercontent.com/30131033/118448443-ad452080-b6fa-11eb-83ea-0f45a0138cd7.png)

**Comment by IbrahimAlgadi** [comment]
> You can solve this issue by defining the network where the peer and the artifacts are in
> 
> ![image](https://user-images.githubusercontent.com/30131033/118448443-ad452080-b6fa-11eb-83ea-0f45a0138cd7.png)

Adding the external then adding the name of the other network

**Comment by Vivek-Jd-18** [comment]
in my case the issue was this:

port described of peer in my connection.json and port on which my peer organisation was running were different, so after correcting ports I resolved that issue.
